--- Documentation/Makefile
+++ Documentation/Makefile
@@ -1,3 +1,3 @@
 obj-m := DocBook/ accounting/ auxdisplay/ connector/ \
 	filesystems/ filesystems/configfs/ ia64/ laptops/ networking/ \
-	pcmci spi/ timers/ video4linux/ vm/ watchdog/src/
+	pcmci spi/ timers/ vm/ watchdog/src/
